### PR TITLE
od: remove long double

### PR DESCRIPTION
**Pull request by chlongv**
Remove -t fL support for the od applet. It was anyhow non-functional as the use f128 representation was not compatible with the c representation, resulting in different results between rustybox and the classic od.

This allows to remove the f128 dependency as it is the only use of it and this should help for the cross-compilation that currently fails with f128.

### CODE REVIEW

**Comment by samuela** [comment]
Thanks for the PR @chlongv ! It'll be great to finally be rid of f128. Curious that the f128 version was buggy... that seems like an issue with c2rust.

The CI error is my fault... I'll get that fixed ASAP.

**Comment by samuela** [comment]
Ok, should be fixed in https://github.com/samuela/rustybox/commit/a1360f80cfff422cdf64ad3f63156ac6f79ba512

**Comment by chlongv** [comment]
> Thanks for the PR @chlongv ! It'll be great to finally be rid of f128. Curious that the f128 version was buggy... that seems like an issue with c2rust.
> 

Have a look at this thread: https://github.com/rust-lang/rust-bindgen/issues/1549

Doing some tests I have noticed the difference: with a binary 0.0 long double (confirmed with the "real" od), rustybox's od gave me nan (not a number).

**Review by samuela — APPROVED** [review]
Looks good!

**Pull request merged**
