### PR TITLE
Allow to build on more platforms

### PR DESCRIPTION
**Pull request by kellda**
This allows to also build on platforms where `libc::c_ulong` is `u32` instead of `u64` or where `libc::c_char` is `u8` instead of `i8`.

### CODE REVIEW

**Comment by samuela** [comment]
I don't understand the point here... Using `libc` allows us to be more platform-independent than hardcoding primitive types. What platforms does it not compile on at the moment that you're concerned about?

**Comment by playerdefault** [comment]
It doesn't compile on Windows because of this issue. See https://github.com/samuela/rustybox/issues/29

**Comment by kellda** [comment]
In fact I'm not trying to build for windows

**Comment by kellda** [comment]
> Using libc allows us to be more platform-independent than hardcoding primitive types

It should. But when `uint64_t` get preprocessed to `unsigned long`, which is transpiled to `libc::c_ulong` which is defined as `u32` on some platforms, it seems clear that it won't work. (see also immunant/c2rust/issues/259)

Btw my target triple is `armv7-unknown-linux-gnueabihf`

**Comment by samuela** [comment]
@kellda Thanks for the pointer to https://github.com/immunant/c2rust/issues/259. Besides compilation, the main blocker to adding support for other target triples is being able to add them to CI. GitHub Actions doesn't have support ARM support at the moment, except through self-hosted runners (https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/). I also don't have an ARM device that I could really test on.

**Comment by kellda** [comment]
Well I have an ARM device on which I tried to build this. I was able to get rid to all type mismatch errors but I still couldn't build (likely because of the amount of RAM needed). Moreover once built it may not work/crash because of hardcoded `extern "C"`.

Now that I tried, I think that c2rust output just isn't portable. Maybe you should state that it only works on 64 bits, little-endian platforms with glibc and wait every util to be rewritten in better Rust before trying to build it somewhere else.

**Comment by samuela** [comment]
Yeah, these are all uphill battles to rid ourselves of these c2rust artifacts. I think you're right that the best way forward for increased cross platform support is to start porting the applets to be cross platform one at a time. This discussion also came up in https://github.com/samuela/rustybox/issues/29.

**Comment by kellda** [comment]
So sounds like this pull request can be closed, if you're ok with this

**Comment by samuela** [comment]
Yeah, I think let's close this for now and focus on getting more apps rust-ified with CI tasks for building those on multiple platforms. Then we can revisit some of these changes with more clarity.

**Pull request closed without merging**
